### ISSUE TITLE
Feature 1: User can search for a card 

### ISSUE THREAD

**Issue by easton-morris** [easton-morris/lfz-final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for a specific card in the modal

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking the "Add a Card" button will open a modal that can be used to search for a specific card by card name

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/75236087/142718347-2a8def93-a9da-4d2a-b2eb-413ec7947698.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to include a route to populate the cards table with the most up-to-date cards and card objects (not needed, using the SDK to make API calls)

### ⚡ Client

- [x] Create a component to be the button that opens the modal
- [x] Create a Modal component for searching the card and letting the user select it
- [x] Create a cardSearchItem component to populate the list with
- [x] Create a cardSearchList component to display the list items

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] Create helper functions for filtering the list using the search terms
- [x] Create a function to update the list onSubmit of the search box's value
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by easton-morris** [comment]
![cardSearchDT](https://user-images.githubusercontent.com/75236087/145153027-3512711a-0bc6-4606-9b3d-dc1d164fd367.gif)

**Comment by easton-morris** [comment]
![cardSearchMobile](https://user-images.githubusercontent.com/75236087/145153167-a3d82886-07c9-4da9-b22c-95858b721de2.gif)
