### ISSUE TITLE
Bug: script for card update doesnt give status of updates

### ISSUE THREAD

**Issue by easton-morris** [easton-morris/lfz-final-project#10]
#### Desired Behavior

> ##### The app should ...

tell the dev when the script is done running

#### Actual Behavior

> ##### The app does this instead ...

ends with no print in the terminal

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

run the script with above basic params

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] ... 
- [x] ...
- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.

**Comment by easton-morris** [comment]
Updates now given with a `finally` method. also logged last page with the error. insert SQL also includes card that was updated.

**Comment by easton-morris** [comment]
![image](https://user-images.githubusercontent.com/75236087/145789814-b561b5ac-4e39-4d61-98be-59a3967706a2.png)

**Comment by easton-morris** [comment]
All 14359 cards and their data loaded.
