### ISSUE TITLE
Feature 4: User can create a new list

### ISSUE THREAD

**Issue by easton-morris** [easton-morris/lfz-final-project#15]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click the "+new list" button to create a new blank list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click the lists drop down and click the "+new list" button to make a new list

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have path for pulling a user's lists to display them
- [x] Update routes to have the correct prefixes
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update list component to check list number
- [x] Update Header component to add a handler for new list button
- [x] Update Header component to check for the number of lists for the user and display them all in the drop down
- [x] Update List to check for listId and pull cards
- [x] Use hash routing to display the correct card info on prop update

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [x] clean up header design
- [x] add error-handling for lack of userId
- [x] add validation
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.

**Comment by easton-morris** [comment]
![image](https://user-images.githubusercontent.com/75236087/172147173-973fc867-830e-4bcc-95c6-362004480f5b.png)
 can't delete card from another list

**Comment by easton-morris** [comment]
Fixed delete bug

**Comment by easton-morris** [comment]
can now add a list and give it a name. also have it assigned to the user
