### ISSUE TITLE
Feature 2: User can add a card to the chase list

### ISSUE THREAD

**Issue by easton-morris** [easton-morris/lfz-final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a card to their chase list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to highlight a card in the modal, then click the "Add Card" button to add it to their list

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/75236087/142970244-2fbc16a6-316a-4687-a767-1bee299056a6.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to route a PUT request with card data to update a cardList
- [x] add a get and post route for new data
- [x] #13
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update searchModal to have a click handler for click events to add the card to state for adding to the list via add card btton
- [x] Update "SAVE" button to send the PUT request and receive the updated list

### 🧑‍⚕️ Clean Up

- [x] Test to make sure the list is getting updated in state
- [x] Test to make sure the PUT request is getting sent when "SAVE" button is clicked
- [x] Test to make sure you cannot create multiple lists in succession
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by easton-morris** [comment]
finished and tested.
