### ISSUE TITLE
Feature 3: User can remove a card from their chase list

### ISSUE THREAD

**Issue by easton-morris** [easton-morris/lfz-final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can remove a card from the list at will

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user will click the "Remove" button and will be prompted with a modal to confirm. if confirmed, card will be removed

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/75236087/146484300-14856012-d9ef-410d-9c23-d94920584db5.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle a delete request for removing a card from cardLists
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to pop up when the remove button is clicked
- [x] Update list component to have the handler work on it

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by easton-morris** [comment]
closing. feature works. will adjust mobile format after list creation routes and pages.
