### ISSUE TITLE
Feature 5: User can erase all cards on the chase list OR delete the list itself

### ISSUE THREAD

**Issue by easton-morris** [easton-morris/lfz-final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to include route for deleting whole lists and route for deleting all cards from a list
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to present and handle delete options
- [x] Update header component to update when deleted
- [x] Update all components to receive user logged in values for next feature

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [x] Test fitting of card menus in modes
- [x] Test to make sure all cards are deleted
- [x] Make sure deleting list routes to Home successfully
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
