### ISSUE TITLE
Feature 6: User can sign-in and sign-out

### ISSUE THREAD

**Issue by easton-morris** [easton-morris/lfz-final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to allow for signing in by checking against UN and PW
- [x] Update route for signing up and responding with correct items for routing
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update login page component to have the correct forms and validation for logins
- [x] Update Header to include logout button and hide the Lists if logged out

### 🧑‍⚕️ Clean Up

- [x] Make sure the buttons require validation
- [x] Make sure error messages are shown for bad logins
- [x] make sure auth is set up for fetches and that auth works
- [x] refactoring login handling to go through localstorage
- [x] double check active list handling is in tact
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
