### ISSUE TITLE
Feature 0: User can navigate with the header

### ISSUE THREAD

**Issue by easton-morris** [easton-morris/lfz-final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click header or menu items to navigate

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click either the link, icon, or menu item to navigate the site and app

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component to display the header
- [x] Update app component to include the header

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
