### ISSUE TITLE
Bug: search breaks when you include a space

### ISSUE THREAD

**Issue by easton-morris** [easton-morris/lfz-final-project#9]
#### Desired Behavior

> ##### The app should ...

populate the list based on the query

#### Actual Behavior

> ##### The app does this instead ...

breaks when you include a space in the query

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

type in a search query with a space in it

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [ ] change the template literal to remove the space and search correctly
- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.

**Comment by easton-morris** [comment]
fixed
